#!/bin/zsh

function links {
    rm -rf ~/$1
    ln -s `pwd`/$2 ~/$1
}

links .vimrc         vim/vimrc
links .ctags         vim/ctags
links .vim           vim

links .profile       zsh/profile
links .zshrc         zsh/zshrc
links .zsh           zsh
links .gitconfig     git/gitconfig
links .gitignore     git/gitignore
links .jshintrc      nodejs/jshintrc
links .tern-project  nodejs/tern-project

links bin/startup.py python/startup.py
links .Xmodmap       ubuntu/Xmodmap

