#!/bin/bash

# Add debian repository
sudo add-apt-repository -y ppa:chris-lea/node.js

sudo apt-get update

sudo apt-get -y install bless build-essential ctags git mercurial nodejs nodejs-dev rlwrap ruby vim zsh \
                        haxe gimp gnome-shell inkscape tree ibus-mozc zlib1g-dev

# install python packages
suto apt-get -y install python2.7 python3 python-dev python3-dev python-pip python3-pip python-selenium python-sqlite
sudo pip install  flask fabric ipython PyYAML sphinx virtualenv virtualenvwrapper

# install oh-my-zsh
wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh

# install gems
sudo gem install rake sass

# init virtualenv
mkdir -p ~/.envs
mkdir -p ~/work
mkdir -p ~/lib
mkdir -p ~/bin
