ZSH=$HOME/.oh-my-zsh

#ZSH_THEME="robbyrussell"
ZSH_THEME="kphoen"

DISABLE_AUTO_UPDATE="true" 
plugins=(git)


source $ZSH/oh-my-zsh.sh

# disable autocorrect
unsetopt correct_all

# Customize to your needs...
export PYTHONSTARTUP=$HOME/bin/startup.py
export TERM=xterm-256color

alias gvim="gvim -f"
alias ln="ln -sf"
alias gs="git status -s"
alias gst="git status"
alias gr="git gr"
alias gl="git log"
alias gp="git push origin master"
alias im="vim"
alias mo="mocha -u tdd"

. $HOME/.zsh/z.sh

# virtualenv
source /usr/local/bin/virtualenvwrapper.sh
export WORKEN_HOME=$HOME/.envs

# env var
export EDITOR=vim
export PAGER=less
export WORK=$HOME/work
export OSS=$WORK/oss

# Z autojump
_Z_CMD=j
source $HOME/.zsh/z.sh
precmd() {
  _z --add "$(pwd -P)"
}

# Path
export PATH=$PATH:$HOME/.cabal/bin
export CPLUS_INCLUDE_PATH=/home/norahiko/.node-gyp/0.10.26/src:$CPLUS_INCLUDE_PATH

# vim command friendly
stty -ixon -ixoff


